/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  safelist: [
    'sns-button',
    'sns-button-twitter',
    'sns-button-line',
    'sns-button-instagram',
    'sns-button-facebook',
    'sns-share-grid',
    'bg-giver-light',
    'bg-giver',
    'bg-giver-dark',
    'bg-matcher-light',
    'bg-matcher',
    'bg-matcher-dark',
    'bg-taker-light',
    'bg-taker',
    'bg-taker-dark',
    'text-giver',
    'text-matcher',
    'text-taker',
    'bg-primary',
    'bg-primary-light',
    'bg-primary-dark',
    'bg-accent',
    'bg-accent-light',
    'bg-accent-dark',
    'bg-secondary',
    'bg-secondary-light',
    'bg-secondary-dark',
    'bg-neutral',
    'bg-neutral-light',
    'bg-neutral-dark',
    'bg-base',
    'bg-base-100',
    'bg-base-200',
    'bg-base-300',
    'text-primary',
    'text-accent',
    'text-secondary',
    'text-neutral',
    'text-neutral-light',
    'border-primary',
    'border-accent',
    'border-secondary',
    'border-base-300',
    'hover:bg-primary-light/10',
    'hover:bg-primary/10',
    'hover:bg-primary-dark/10',
    'hover:bg-accent-light/10',
    'hover:bg-accent/10',
    'hover:bg-accent-dark/10',
    'hover:bg-secondary-light/10',
    'hover:bg-secondary/10',
    'hover:bg-secondary-dark/10',
    'prose',
    'prose-lg',
    'max-w-none',
    'prose-h2:text-gray-800',
    'prose-h3:text-gray-700',
  ],
  theme: {
    extend: {
      colors: {
        'giver': {
          light: '#8B5CF6',
          DEFAULT: '#7C3AED',
          dark: '#6D28D9',
        },
        'matcher': {
          light: '#3B82F6',
          DEFAULT: '#2563EB',
          dark: '#1D4ED8',
        },
        'taker': {
          light: '#F59E0B',
          DEFAULT: '#D97706',
          dark: '#B45309',
        },
        'success': '#10B981',
        'warning': '#F97316',
        'error': '#EF4444',
        'surface': {
          light: '#F9FAFB',
          DEFAULT: '#F3F4F6',
          dark: '#E5E7EB',
        },
        primary: {
          DEFAULT: 'var(--color-primary)',
          light: 'var(--color-primary-light)',
          dark: 'var(--color-primary-dark)',
        },
        supporter: {
          DEFAULT: 'var(--color-supporter)',
          light: 'var(--color-supporter-light)',
          dark: 'var(--color-supporter-dark)',
        },
        cooperative: {
          DEFAULT: 'var(--color-cooperative)',
          light: 'var(--color-cooperative-light)',
          dark: 'var(--color-cooperative-dark)',
        },
        balanced: {
          DEFAULT: 'var(--color-balanced)',
          light: 'var(--color-balanced-light)',
          dark: 'var(--color-balanced-dark)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
        },
        background: 'var(--color-background)',
        card: 'var(--color-card)',
        accent: {
          DEFAULT: 'var(--color-accent)',
          light: 'var(--color-accent-light)',
          dark: 'var(--color-accent-dark)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          light: 'var(--color-secondary-light)',
          dark: 'var(--color-secondary-dark)',
        },
        neutral: {
          DEFAULT: 'var(--color-neutral)',
          light: 'var(--color-neutral-light)',
          dark: 'var(--color-neutral-dark)',
        },
        base: {
          DEFAULT: 'var(--color-base)',
          100: 'var(--color-base-100)',
          200: 'var(--color-base-200)',
          300: 'var(--color-base-300)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'M PLUS Rounded 1c', 'sans-serif'],
        rounded: ['M PLUS Rounded 1c', 'sans-serif'],
      },
      fontSize: {
        'display': ['2.5rem', { lineHeight: '1.2', fontWeight: '700' }],
        'heading-1': ['2rem', { lineHeight: '1.3', fontWeight: '700' }],
        'heading-2': ['1.5rem', { lineHeight: '1.4', fontWeight: '600' }],
        'heading-3': ['1.25rem', { lineHeight: '1.5', fontWeight: '600' }],
        'body-large': ['1.125rem', { lineHeight: '1.6' }],
        'body': ['1rem', { lineHeight: '1.6' }],
        'body-small': ['0.875rem', { lineHeight: '1.5' }],
      },
      backgroundImage: {
        'mesh': 'linear-gradient(to right bottom, rgba(139, 92, 246, 0.05), rgba(59, 130, 246, 0.05))',
        'primary-gradient': 'linear-gradient(to bottom right, rgba(26, 154, 157, 0.1), rgba(21, 131, 133, 0.05))',
        'accent-gradient': 'linear-gradient(to bottom right, rgba(107, 45, 144, 0.1), rgba(87, 36, 118, 0.05))',
        'secondary-gradient': 'linear-gradient(to bottom right, rgba(78, 205, 196, 0.1), rgba(57, 179, 170, 0.05))',
        'giver-gradient': 'linear-gradient(to bottom right, rgba(139, 92, 246, 0.1), rgba(109, 40, 217, 0.05))',
        'matcher-gradient': 'linear-gradient(to bottom right, rgba(59, 130, 246, 0.1), rgba(29, 78, 216, 0.05))',
        'taker-gradient': 'linear-gradient(to bottom right, rgba(245, 158, 11, 0.1), rgba(180, 83, 9, 0.05))',
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: '#1F2937',
            a: {
              color: 'var(--color-primary)',
              '&:hover': {
                color: 'var(--color-primary-dark)',
              },
            },
            h2: {
              color: '#1F2937',
              fontWeight: '700',
            },
            h3: {
              color: '#374151',
              fontWeight: '600',
            },
            strong: {
              color: '#111827',
              fontWeight: '600',
            },
            li: {
              color: '#1F2937',
              margin: '0.5em 0',
            },
            ul: {
              margin: '1.5em 0',
            },
            'ul > li': {
              paddingLeft: '0.25em',
            },
            'ul > li::marker': {
              color: 'var(--color-primary)',
            },
            blockquote: {
              color: '#1F2937',
              borderLeftColor: 'var(--color-primary-light)',
            },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
} 