export const ACTIVITY_POINTS = {
  CREATE_CONTENT: 10,
  PROVIDE_FEEDBACK: 5,
  RECEIVE_FEEDBACK: 2,
  COMPLETE_RESOURCE: 8,
  SHARE_RESOURCE: 3,
  CONSUME_CONTENT: 1,
  ASK_QUESTION: 2,
  ANSWER_QUESTION: 5
} as const;

export const ACHIEVEMENT_THRESHOLDS = {
  BEGINNER: 50,
  INTERMEDIATE: 200,
  ADVANCED: 500,
  EXPERT: 1000
} as const;

export type ActivityPointsKey = keyof typeof ACTIVITY_POINTS; 